classifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('specimen/', include('specimen.urls')),
    path('trees/', include('trees.urls')),
    path('epiphytes/', include('epiphytes.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locations/urls.py
from django.urls import path

from .views import LocationAddView
from .views import LocationListView
from .views import LocationUpdateView


app_name = 'locations'

urlpatterns = [
    path('', LocationListView.as_view(), name='list'),

    path(
        'create/',
        LocationAddView.as_view(),
        name='create'),

    path(
        'update/<int:pk>/',
        LocationUpdateView.as_view(),
        name='update'),
]

trees/urls.py
from django.urls import path
from .views import (
    TreeCreateView,
    TreeListView,
    TreeUpdateView,
)


app_name = 'trees'

urlpatterns = [
    path('list/', TreeListView.as_view(),
        name='list'),
    path('create/', TreeCreateView.as_view(),
        name='create'),
    path('<int:pk>/update/', TreeCreateView.as_view(),
        name='update'),
]

locations/models.py
from django.db import models


class Location(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

locations/forms.py
from django import forms

from .models import Location


class LocationForm(forms.ModelForm):
    """
    A form for adding or updating locations.
    """

    class Meta:
        model = Location
        fields = ['name']

locations/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.shortcuts import render

from .forms import LocationForm
from .models import Location


class LocationListView(ListView):
    """
    View for listing locations.
    """

    model = Location
    template_name = 'locations/list_location.html'


class LocationAddView(CreateView):
    """
    Form view for adding locations.
    """

    model = Location
    form_class = LocationForm
    template_name = 'locations/add_location.html'
    success_url = reverse_lazy('locations:list')


class LocationUpdateView(UpdateView):
    """
    Form view for updating locations.
    """

    model = Location
    form_class = LocationForm
    template_name = 'locations/update_location.html'
    success_url = reverse_lazy('locations:list')

locations/templates/locations/add_location.html
{% extends 'default-form.html' %}

{% block title %}
    Add Location
{% endblock title %}

{% block form %}
    {{ form }}
{% endblock form %}

locations/templates/locations/list_location.html
{% extends 'base.html' %}

{% block title %}
    Locations
{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex flex-row-reverse mb-3" id="header-buttons">
        <a href="{% url 'locations:create' %}">
            <button class="btn btn-success">
                Add Location
            </button>
        </a>
    </div>
    <table class="table table-condensed">
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.name }}</td>
            <td>
                <a class="btn btn-sm btn-icon btn-secondary" href="{% url 'locations:update' object.pk %}">
                    <i class="fa fa-pencil"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</div>
{% endblock %}

locations/templates/locations/update_locations.html
{% extends 'default-form.html' %}

{% block title %}
    Update Location - {{ object.name }}
{% endblock title %}

{% block form %}
    {{ form }}
{% endblock form %}