classifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('specimen/', include('specimen.urls')),
    path('trees/', include('trees.urls')),
    path('epiphytes/', include('epiphytes.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

specimen/urls.py
from django.urls import path

from .views import (
    GenerateAllSpecimensView,
    CreateSpecimenView,
    UpdateSpecimenView,
    SpecimenListView,
    SpecimenDetailView,
    SpecimenDeleteView,
    AddDirectionDetailsView,
    SpecimenSamplesFormView,
    NorthDeleteSampleImageView,
    EastDeleteSampleImageView,
    WestDeleteSampleImageView,
    SouthDeleteSampleImageView
)


app_name = 'specimen'

urlpatterns = [
    path('', SpecimenListView.as_view(),
        name='list'),
    path('detail/<int:pk>/', SpecimenDetailView.as_view(),
        name='detail'),
    path('new/', CreateSpecimenView.as_view(),
        name='create'),
    path('update/<int:pk>/', UpdateSpecimenView.as_view(),
        name='update'),
    path('new-direction-details/<int:pk>/', AddDirectionDetailsView.as_view(),
        name='new_direction_details'),
    path('direction-samples/<int:pk>/', SpecimenSamplesFormView.as_view(),
        name='samples'),
    path('north/delete/<int:pk>/', NorthDeleteSampleImageView.as_view(),
        name='delete_north'),
    path('east/delete/<int:pk>/', EastDeleteSampleImageView.as_view(),
        name='delete_east'),
    path('west/delete/<int:pk>/', WestDeleteSampleImageView.as_view(),
        name='delete_west'),
    path('south/delete/<int:pk>/', SouthDeleteSampleImageView.as_view(),
        name='delete_south'),
    path('all_specimens_report/', GenerateAllSpecimensView.as_view(),
        name='all_specimens_report'),
    path('delete/<int:pk>/', SpecimenDeleteView.as_view(),
        name='delete'),
]

trees/urls.py
from django.urls import path
from .views import (
    TreeCreateView,
    TreeListView,
    TreeUpdateView,
)


app_name = 'trees'

urlpatterns = [
    path('list/', TreeListView.as_view(),
        name='list'),
    path('create/', TreeCreateView.as_view(),
        name='create'),
    path('<int:pk>/update/', TreeCreateView.as_view(),
        name='update'),
]

direction/models.py
from statistics import mean

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.files.storage import FileSystemStorage

from epiphytes.models import EpiphyticOrganism
from specimen.models import Specimen


class Directions(models.TextChoices):
    NORTH = 'N', _('North')
    EAST = 'E', _('East')
    WEST = 'W', _('West')
    SOUTH = 'S', _('South')


class StateOfDecay(models.TextChoices):
    INTACT = 'i', _('Intact')
    MODERATELY_INTACT = 'mi', _('Moderately Intact')
    LOOSE = 'l', _('Loose')


class Texture(models.TextChoices):
    SMOOTH = 's', _('Smooth')
    ROUGH = 'r', _('Rough')


class DirectionSampleDetailsModel(models.Model):
    specimen = models.OneToOneField(Specimen, on_delete=models.CASCADE)
    ph_level_1 = models.DecimalField(
        max_digits=19,
        decimal_places=2,
        null=True,
        blank=True,
    )
    ph_level_2 = models.DecimalField(
        max_digits=19,
        decimal_places=2,
        null=True,
        blank=True,
    )
    ph_level_3 = models.DecimalField(
        max_digits=19,
        decimal_places=2,
        null=True,
        blank=True,
    )
    state_of_decay = models.CharField(
        max_length=8,
        choices=StateOfDecay.choices,
        default=StateOfDecay.INTACT
    )
    bark_texture = models.CharField(
        max_length=8,
        choices=Texture.choices,
        default=Texture.SMOOTH
    )
    stain = models.BooleanField(default=True)

    class Meta:
        abstract = True

    @property
    def average_ph(self):
        ph_list = []
        for ph in [
                    self.ph_level_1,
                    self.ph_level_2,
                    self.ph_level_3
                ]:
            if ph:
                ph_list.append(ph)
        return round(mean(ph_list), 2)


class NorthDetails(DirectionSampleDetailsModel):
    def __str__(self):
        return f'{self.specimen.name}'


class EastDetails(DirectionSampleDetailsModel):
    def __str__(self):
        return f'{self.specimen.name}'


class WestDetails(DirectionSampleDetailsModel):
    def __str__(self):
        return f'{self.specimen.name}'


class SouthDetails(DirectionSampleDetailsModel):
    def __str__(self):
        return f'{self.specimen.name}'


class DirectionOrganism(models.Model):
    specimen = models.ForeignKey(Specimen, on_delete=models.CASCADE)
    epiphytic_organism = models.ForeignKey(EpiphyticOrganism, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class NorthOrganism(DirectionOrganism):
    def __str__(self):
        return f'{self.epiphytic_organism.name}'


class EastOrganism(DirectionOrganism):
    def __str__(self):
        return f'{self.epiphytic_organism.name}'


class WestOrganism(DirectionOrganism):
    def __str__(self):
        return f'{self.epiphytic_organism.name}'


class SouthOrganism(DirectionOrganism):
    def __str__(self):
        return f'{self.epiphytic_organism.name}'


class DirectionImagesModel(models.Model):
    specimen = models.ForeignKey(Specimen, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class NorthImages(DirectionImagesModel):
    image = models.ImageField(blank=True, null=True,
        upload_to='specimen_images/north/')

    def __str__(self):
        return f'{self.specimen.name} | {self.image}'


class EastImages(DirectionImagesModel):
    image = models.ImageField(blank=True, null=True,
        upload_to='specimen_images/east/')

    def __str__(self):
        return f'{self.specimen.name} | {self.image}'


class WestImages(DirectionImagesModel):
    image = models.ImageField(blank=True, null=True,
        upload_to='specimen_images/west/',
        storage=FileSystemStorage())

    def __str__(self):
        return f'{specimen.name} | {self.image}'


class SouthImages(DirectionImagesModel):
    image = models.ImageField(blank=True, null=True,
        upload_to='specimen_images/south/')

    def __str__(self):
        return f'{self.specimen.name} | {self.image}'

specimen/models.py
import datetime
import decimal

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Specimen(models.Model):
    name = models.CharField(max_length=256, blank=True, default='')
    code = models.CharField(max_length=128, blank=True, default='')
    host_tree = models.ForeignKey('trees.Tree', on_delete=models.CASCADE)
    location = models.ForeignKey('locations.Location', on_delete=models.CASCADE)
    latitude = models.CharField(max_length=256, blank=True, default='')
    longhitude = models.CharField(max_length=256, blank=True, default='')
    dbh = models.DecimalField(
        max_digits=19,
        decimal_places=2
    )
    collection_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.name} - {self.code}'

    @property
    def get_distinct_organisms(self):
        north = self.northorganism_set.all()
        east = self.eastorganism_set.all()
        west = self.westorganism_set.all()
        south = self.southorganism_set.all()

        distinct_organisms = []

        for collection in [north, east, west, south]:
            for item in collection:
                organism = item.epiphytic_organism
                if organism.name not in distinct_organisms:
                    distinct_organisms.append(organism.name)

        return distinct_organisms

specimen/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)

from core.helpers import slicedict
from core.helpers import to_dictionary_list
from core.reports import AllSpecimens
from core.views import ReportView
from direction.forms import (
    NorthDetailsForm,
    EastDetailsForm,
    WestDetailsForm,
    SouthDetailsForm,
)
from direction.models import (
    NorthDetails,
    EastDetails,
    WestDetails,
    SouthDetails,
    NorthOrganism,
    EastOrganism,
    WestOrganism,
    SouthOrganism,
    NorthImages,
    EastImages,
    WestImages,
    SouthImages,
)
from direction.models import StateOfDecay
from direction.models import Texture
from epiphytes.models import EpiphyticOrganism
from trees.models import Tree

from .models import Specimen
from .forms import SpecimenForm


class GenerateAllSpecimensView(ReportView):
    report_class = AllSpecimens


class CreateSpecimenView(CreateView):
    """
    Form view for adding specimens.
    """

    model = Specimen
    form_class = SpecimenForm
    template_name = 'specimen/create-specimen.html'

    def get_success_url(self):
        return reverse_lazy('specimen:detail',
            kwargs={'pk': self.object.pk})


class SpecimenListView(ListView):
    """
    Lists all specimens.
    """

    model = Specimen
    template_name = 'specimen/list-specimen.html'


class SpecimenDetailView(DetailView):
    """
    Detail view for specimens.
    """

    model = Specimen
    template_name = 'specimen/detail-specimen.html'

    def get_context_data(self, **kwargs):
        context = super(SpecimenDetailView, self).get_context_data(**kwargs)

        pk = self.kwargs['pk']
        specimen = Specimen.objects.get(id=pk)

        try:
            context['north_details'] = NorthDetails.objects.get(specimen=specimen)
        except NorthDetails.DoesNotExist:
            context['north_details'] = None

        try:
            context['east_details'] = EastDetails.objects.get(specimen=specimen)
        except EastDetails.DoesNotExist:
            context['east_details'] = None

        try:
            context['west_details'] = WestDetails.objects.get(specimen=specimen)
        except WestDetails.DoesNotExist:
            context['west_details'] = None

        try:
            context['south_details'] = SouthDetails.objects.get(specimen=specimen)
        except SouthDetails.DoesNotExist:
            context['south_details'] = None

        context['north_organisms'] = [
            i.epiphytic_organism for i in specimen.northorganism_set.all()]
        context['east_organisms'] = [
            i.epiphytic_organism for i in specimen.eastorganism_set.all()]
        context['west_organisms'] = [
            i.epiphytic_organism for i in specimen.westorganism_set.all()]
        context['south_organisms'] = [
            i.epiphytic_organism for i in specimen.southorganism_set.all()]

        return context


class UpdateSpecimenView(UpdateView):
    """
    View for updating specimens.
    """

    model = Specimen
    form_class = SpecimenForm
    template_name = 'specimen/update-specimen.html'

    def get_success_url(self):
        return reverse_lazy('specimen:detail',
            kwargs={'pk': self.object.pk})


class SpecimenDeleteView(DeleteView):
    """
    View for deleting specimens.
    """

    model = Specimen

    def get_success_url(self, **kwargs):
        return reverse_lazy('specimen:list')

class AddDirectionDetailsView(View):
    template_name = 'specimen/direction-details.html'

    def get_organism_pks(self, post_request, direction):
        return list(
            slicedict(
                post_request,
                f'{direction}Epiphyte',
                removeEmpty=True)
            .values()
        )

    def save_organisms(self, specimen, organisms_set, organism_model):
        for organism_pk in organisms_set:
            organism = EpiphyticOrganism.objects.get(id=organism_pk)
            organism_object = organism_model.objects.get_or_create(
                specimen=specimen, epiphytic_organism=organism)

    def delete_excluded_organisms(self, specimen):
        north_organisms = specimen.northorganism_set.all()
        east_organisms = specimen.eastorganism_set.all()
        west_organisms = specimen.westorganism_set.all()
        south_organisms = specimen.southorganism_set.all()

        for organisms, model in [
                    (north_organisms, NorthOrganism),
                    (east_organisms, EastOrganism),
                    (west_organisms, WestOrganism),
                    (south_organisms, SouthOrganism)
                ]:
            self.delete_organisms(organisms, model)

    def delete_organisms(self, organisms, model):
        for organism in organisms:
            for organism in organisms:
                model.objects.filter(id=organism.pk).delete()

    def save_details(self, specimen, north, east, west, south):
        for direction, model in [
                    (north, NorthDetails),
                    (east, EastDetails),
                    (west, WestDetails),
                    (south, SouthDetails),
                ]:
            details, created = model.objects.get_or_create(specimen=specimen)
            if direction['ph_level_1']:
                details.ph_level_1 = direction['ph_level_1']
            if direction['ph_level_2']:
                details.ph_level_2 = direction['ph_level_2']
            if direction['ph_level_3']:
                details.ph_level_3 = direction['ph_level_3']
            if direction['state_of_decay']:
                details.state_of_decay = direction['state_of_decay']
            if direction['texture']:
                details.texture = direction['texture']
            details.stain = True if direction['stain'] == 'on' else False
            details.save()

    def get(self, request, pk, *args, **kwargs):
        context = {}
        specimen = Specimen.objects.get(id=pk)
        epiphytes = EpiphyticOrganism.objects.all()

        context['epiphytes'] = epiphytes

        try:
            north_details = NorthDetails.objects.get(specimen=specimen)
        except NorthDetails.DoesNotExist:
            north_details = None

        try:
            east_details = EastDetails.objects.get(specimen=specimen)
        except EastDetails.DoesNotExist:
            east_details = None

        try:
            west_details = WestDetails.objects.get(specimen=specimen)
        except WestDetails.DoesNotExist:
            west_details = None

        try:
            south_details = SouthDetails.objects.get(specimen=specimen)
        except:
            south_details = None

        if north_details:
            context['north_details'] = north_details
        if east_details:
            context['east_details'] = north_details
        if west_details:
            context['west_details'] = north_details
        if south_details:
            context['south_details'] = north_details

        context['north_organisms'] = [
            i.epiphytic_organism.pk for i in specimen.northorganism_set.all()]
        context['east_organisms'] = [
            i.epiphytic_organism.pk for i in specimen.eastorganism_set.all()]
        context['west_organisms'] = [
            i.epiphytic_organism.pk for i in specimen.westorganism_set.all()]
        context['south_organisms'] = [
            i.epiphytic_organism.pk for i in specimen.southorganism_set.all()]

        context['state_of_decay_choices'] = to_dictionary_list(StateOfDecay.choices)
        context['texture_choices'] = to_dictionary_list(Texture.choices)

        return render(request, self.template_name, context=context)

    def post(self, request, pk, *args, **kwargs):
        specimen = Specimen.objects.get(id=pk)

        north_ph_1 = request.POST.get('northPH1')
        north_ph_2 = request.POST.get('northPH2')
        north_ph_3 = request.POST.get('northPH3')
        north_state_of_decay = request.POST.get('northStateOfDecay')
        north_texture = request.POST.get('northTexture')
        north_stain = request.POST.get('northStain')

        east_ph_1 = request.POST.get('eastPH1')
        east_ph_2 = request.POST.get('eastPH2')
        east_ph_3 = request.POST.get('eastPH3')
        east_state_of_decay = request.POST.get('eastStateOfDecay')
        east_texture = request.POST.get('eastTexture')
        east_stain = request.POST.get('eastStain')

        west_ph_1 = request.POST.get('westPH1')
        west_ph_2 = request.POST.get('westPH2')
        west_ph_3 = request.POST.get('westPH3')
        west_state_of_decay = request.POST.get('westStateOfDecay')
        west_texture = request.POST.get('westTexture')
        west_stain = request.POST.get('westStain')

        south_ph_1 = request.POST.get('southPH1')
        south_ph_2 = request.POST.get('southPH2')
        south_ph_3 = request.POST.get('southPH3')
        south_state_of_decay = request.POST.get('southStateOfDecay')
        south_texture = request.POST.get('southTexture')
        south_stain = request.POST.get('southStain')

        north_details = {
            'ph_level_1': north_ph_1,
            'ph_level_2': north_ph_2,
            'ph_level_3': north_ph_3,
            'state_of_decay': north_state_of_decay,
            'texture': north_texture,
            'stain': north_stain,
        }
        east_details = {
            'ph_level_1': east_ph_1,
            'ph_level_2': east_ph_2,
            'ph_level_3': east_ph_3,
            'state_of_decay': east_state_of_decay,
            'texture': east_texture,
            'stain': east_stain,
        }
        west_details = {
            'ph_level_1': west_ph_1,
            'ph_level_2': west_ph_2,

specimen/templates/specimen/add-location.html
{% extends 'default-form.html' %}

{% block title %}
    Add Location
{% endblock title %}

{% block form %}
    {{ form }}
{% endblock form %}

specimen/templates/specimen/create-specimen.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    New Specimen
{% endblock title %}

{% block content %}
    <form class="form" action="." method="post">
        <div class="container">
            {% csrf_token %}
            {% include 'specimen/sample-details-form.html' %}
            <hr />
            <input type="submit" value="Submit"/>
        </div>
    </form>
{% endblock content %}

specimen/templates/specimen/detail-specimen.html
{% extends 'base.html' %}
{% load static %}
{% load core_extras %}

{% block styles %}
<style>
    .sample-image {
        max-width: 8rem;
        min-width: 8rem;
    }

    #modalImage {
        max-width: 28rem;
        min-width: 28rem;
    }
</style>
{% endblock styles%}

{% block title %}
    Specimen Detail - {{ object.name }}
{% endblock title %}

{% block content %}
<div class="card mr-auto mb-3">
    <div class="card-header"><h2>{{ object.name }}</h2></div>
    <div class="card-body">
        <div class="row">
            <div class="col-6">
                <div class="row">
                    <div class="col-6">Code: </div>
                    <div class="col-6">{{ object.code }}</div>
                </div>
                <div class="row">
                    <div class="col-6">Host Tree: </div>
                    <div class="col-6">{{ object.host_tree }}</div>
                </div>
                <div class="row">
                    <div class="col-6">Location: </div>
                    <div class="col-6">{{ object.location }}</div>
                </div>
                <div class="row">
                    <div class="col-6">Latitude: </div>
                    <div class="col-6">{{ object.latitude }}</div>
                </div>
                <div class="row">
                    <div class="col-6">Longhitude: </div>
                    <div class="col-6">{{ object.longhitude }}</div>
                </div>
                <div class="row">
                    <div class="col-6">DBH: </div>
                    <div class="col-6">{{ object.dbh }}</div>
                </div>
                <div class="row">
                    <div class="col-6">Collection Date: </div>
                    <div class="col-6">{{ object.collection_date }}</div>
                </div>
            </div>
            <div class="col-6">
                <div class="d-flex flex-row-reverse">
                    <a class="btn btn-sm btn-danger"  data-toggle="modal" data-target="#deleteConfirmationModal" data-text="Are you sure you want to delete this specimen?" data-href="{% url 'specimen:delete' object.pk %}">
                        Delete
                    </a>
                    <a class="btn btn-warning" href="{% url 'specimen:update' object.pk %}">
                        Edit
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card mr-auto mb-3">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <span>Direction Details</span>
            <a class="btn btn-sm btn-warning" href="{% url 'specimen:new_direction_details' object.pk %}">
                Edit
            </a>
        </div>
    </div>
    <div class="card-body text-center">
        <div class="row">
            <h4 class="col-md-2"></h4>
            <h4 class="col-md-2">N</h4>
            <h4 class="col-md-2">E</h4>
            <h4 class="col-md-2">W</h4>
            <h4 class="col-md-2">S</h4>
            <h4 class="col-md-2">Average</h4>
        </div>

        <div class="row">
            <h6 class="col-md-2">1st PH Level</h6>
            <div class="col-md-2">
                {{ north_details.ph_level_1|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ east_details.ph_level_1|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ west_details.ph_level_1|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ south_details.ph_level_1|floatformat:2 }}
            </div>
        </div>

        <div class="row">
            <h6 class="col-md-2">2nd PH Level</h6>
            <div class="col-md-2">
                {{ north_details.ph_level_2|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ east_details.ph_level_2|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ west_details.ph_level_2|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ south_details.ph_level_2|floatformat:2 }}
            </div>
        </div>

        <div class="row">
            <h6 class="col-md-2">3rd PH Level</h6>
            <div class="col-md-2">
                {{ north_details.ph_level_3|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ east_details.ph_level_3|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ west_details.ph_level_3|floatformat:2 }}
            </div>
            <div class="col-md-2">
                {{ south_details.ph_level_3|floatformat:2 }}
            </div>
        </div>

        <div class="row">
            <h6 class="col-md-2">Epiphytes Present</h6>
            <div class="col-md-2">
                {% for organism in north_organisms %}
                    <span>{{ organism.name }}, </span>
                {% endfor %}
            </div>
            <div class="col-md-2">
                {% for organism in east_organisms %}
                    <span>{{ organism.name }}, </span>
                {% endfor %}
            </div>
            <div class="col-md-2">
                {% for organism in west_organisms %}
                    <span>{{ organism.name }}, </span>
                {% endfor %}
            </div>
            <div class="col-md-2">
                {% for organism in south_organisms %}
                    <span>{{ organism.name }}, </span>
                {% endfor %}
            </div>
        </div>

        <div class="row">
            <h6 class="col-md-2">State of Decay</h6>
            <div class="col-md-2">
                {{ north_details.get_state_of_decay_display }}
            </div>
            <div class="col-md-2">
                {{ east_details.get_state_of_decay_display }}
            </div>
            <div class="col-md-2">
                {{ west_details.get_state_of_decay_display }}
            </div>
            <div class="col-md-2">
                {{ south_details.get_state_of_decay_display }}
            </div>
        </div>

        <div class="row">
            <h6 class="col-md-2">Bark Texture</h6>
            <div class="col-md-2">
                {{ north_details.get_bark_texture_display }}
            </div>
            <div class="col-md-2">
                {{ east_details.get_bark_texture_display }}
            </div>
            <div class="col-md-2">
                {{ west_details.get_bark_texture_display }}
            </div>
            <div class="col-md-2">
                {{ south_details.get_bark_texture_display }}
            </div>
        </div>

        <div class="row">
            <h6 class="col-md-2">Stain</h6>
            <div class="col-md-2">
                <div class="rounded">
                    {% if north_details.stain|is_false %}
                        -
                    {% else %}
                        +
                    {% endif %}
                </div>
            </div>
            <div class="col-md-2">
                <div class="rounded">
                    {% if east_details.stain|is_false %}
                        -
                    {% else %}
                        +
                    {% endif %}
                </div>
            </div>
            <div class="col-md-2">
                <div class="rounded">
                    {% if west_details.stain|is_false %}
                        -
                    {% else %}
                        +
                    {% endif %}
                </div>
            </div>
            <div class="col-md-2">
                <div class="rounded">
                    {% if south_details.stain|is_false %}
                        -
                    {% else %}
                        +
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card mr-auto mb-3">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <span>Direction Samples</span>
            <a class="btn btn-sm btn-warning" href="{% url 'specimen:samples' object.pk %}">
                Edit
            </a>
        </div>
    </div>
    <div class="card-body text-center">
        <div class="row">
            <h4 class="col-md-3">N</h4>
            <h4 class="col-md-3">E</h4>
            <h4 class="col-md-3">W</h4>
            <h4 class="col-md-3">S</h4>
        </div>

        <div class="row">
            <div class="col-md-3">
                {% for image in object.northimages_set.all %}
                    <a data-toggle="modal" data-target="#imageModal" data-image="{{ image.image.url }}" data-direction="North" data-delete="{% url 'specimen:delete_north' image.pk %}">
                        <img class="sample-image" src="{{ image.image.url }}" alt="">
                    </a>
                {% endfor %}
            </div>
            <div class="col-md-3">
                {% for image in object.eastimages_set.all %}
                    <a data-toggle="modal" data-target="#imageModal" data-image="{{ image.image.url }}" data-direction="East" data-delete="{% url 'specimen:delete_east' image.pk %}">
                        <img class="sample-image" src="{{ image.image.url }}" alt="">
                    </a>
                {% endfor %}
            </div>
            <div class="col-md-3">
                {% for image in object.westimages_set.all %}
                    <a data-toggle="modal" data-target="#imageModal" data-image="{{ image.image.url }}" data-direction="West" data-delete="{% url 'specimen:delete_west' image.pk %}">
                        <img class="sample-image" src="{{ image.image.url }}" alt="">
                    </a>
                {% endfor %}
            </div>
            <div class="col-md-3">
                {% for image in object.southimages_set.all %}
                    <a data-toggle="modal" data-target="#imageModal" data-image="{{ image.image.url }}" data-direction="South" data-delete="{% url 'specimen:delete_south' image.pk %}">
                        <img class="sample-image" src="{{ image.image.url }}" alt="">
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block modals %}
    {% include 'modals/delete-modal.html' %}
    {% include 'modals/image-modal.html' %}
{% endblock modals %}

specimen/templates/specimen/list-specimen.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Specimen List
{% endblock title %}

{% block content %}
<div class="container">
    <div class="d-flex flex-row-reverse mb-3" id="header-buttons">
        <a href="{% url 'specimen:all_specimens_report' %}">
            <button class="btn btn-primary">
                Generate Report
            </button>
        </a>
        <a href="{% url 'specimen:create' %}">
            <button class="btn btn-success">
                Add Specimen
            </button>
        </a>
    </div>
    <table class="table table-condensed">
        <tr>
            <th>Name</th>
            <th>Code</th>
            <th>Host Tree</th>
            <th>Location</th>
            <th>Collection Date</th>
            <th>Actions</th>
        </tr>
        {% for object in object_list %}
        <tr>
            <td>
                <a href="{% url 'specimen:detail' object.pk %}">
                    {{ object.name }}
                </a>
            </td>
            <td>{{ object.code }}</td>
            <td>{{ object.host_tree }}</td>
            <td>{{ object.location }}</td>
            <td>{{ object.collection_date|date:"Y-d-m" }}</td>
            <td>
                <a class="btn btn-sm btn-icon btn-warning" href="{% url 'specimen:update' object.pk %}">
                    <i class="fa fa-pencil"></i>
                </a>
                <a class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteConfirmationModal" data-text="Are you sure you want to delete this specimen?" data-href="{% url 'specimen:delete' object.pk %}">
                    <i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

{% block modals %}
    {% include 'modals/delete-modal.html' %}
{% endblock modals %}

specimen/templates/specimen/update-specimen.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Specimen - {{ object.name }}
{% endblock title %}

{% block content %}
<div class="container">
    <h2>Update Specimen</h2>
    <form class="form" action="." method="post">
        {% csrf_token %}
        {% include 'specimen/specimen-form.html' %}
        <input type="submit" value="Update"/>
    </form>
</div>
{% endblock content %}

{% block extra_js %}
<script>
    $(document).ready(() => {
        $('#id_collection_date').flatpickr();
    });
</script>
{% endblock extra_js %}