classifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('specimen/', include('specimen.urls')),
    path('trees/', include('trees.urls')),
    path('epiphytes/', include('epiphytes.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

epiphytes/urls.py
from django.urls import path

from .views import (
    EpiphyticOrganismListView,
    EpiphyticOrganismCreateView,
    EpiphyticOrganismUpdateView,
)


app_name = 'epiphytes'

urlpatterns = [
    path('', EpiphyticOrganismListView.as_view(),
        name='list'),
    path('new/', EpiphyticOrganismCreateView.as_view(),
        name='create'),
    path('update/<int:pk>/', EpiphyticOrganismUpdateView.as_view(),
        name='update')
]

locations/urls.py
from django.urls import path

from .views import LocationAddView
from .views import LocationListView
from .views import LocationUpdateView


app_name = 'locations'

urlpatterns = [
    path('', LocationListView.as_view(), name='list'),

    path(
        'create/',
        LocationAddView.as_view(),
        name='create'),

    path(
        'update/<int:pk>/',
        LocationUpdateView.as_view(),
        name='update'),
]

specimen/urls.py
from django.urls import path

from .views import (
    GenerateAllSpecimensView,
    CreateSpecimenView,
    UpdateSpecimenView,
    SpecimenListView,
    SpecimenDetailView,
    SpecimenDeleteView,
    AddDirectionDetailsView,
    SpecimenSamplesFormView,
    NorthDeleteSampleImageView,
    EastDeleteSampleImageView,
    WestDeleteSampleImageView,
    SouthDeleteSampleImageView
)


app_name = 'specimen'

urlpatterns = [
    path('', SpecimenListView.as_view(),
        name='list'),
    path('detail/<int:pk>/', SpecimenDetailView.as_view(),
        name='detail'),
    path('new/', CreateSpecimenView.as_view(),
        name='create'),
    path('update/<int:pk>/', UpdateSpecimenView.as_view(),
        name='update'),
    path('new-direction-details/<int:pk>/', AddDirectionDetailsView.as_view(),
        name='new_direction_details'),
    path('direction-samples/<int:pk>/', SpecimenSamplesFormView.as_view(),
        name='samples'),
    path('north/delete/<int:pk>/', NorthDeleteSampleImageView.as_view(),
        name='delete_north'),
    path('east/delete/<int:pk>/', EastDeleteSampleImageView.as_view(),
        name='delete_east'),
    path('west/delete/<int:pk>/', WestDeleteSampleImageView.as_view(),
        name='delete_west'),
    path('south/delete/<int:pk>/', SouthDeleteSampleImageView.as_view(),
        name='delete_south'),
    path('all_specimens_report/', GenerateAllSpecimensView.as_view(),
        name='all_specimens_report'),
    path('delete/<int:pk>/', SpecimenDeleteView.as_view(),
        name='delete'),
]

trees/urls.py
from django.urls import path
from .views import (
    TreeCreateView,
    TreeListView,
    TreeUpdateView,
)


app_name = 'trees'

urlpatterns = [
    path('list/', TreeListView.as_view(),
        name='list'),
    path('create/', TreeCreateView.as_view(),
        name='create'),
    path('<int:pk>/update/', TreeCreateView.as_view(),
        name='update'),
]

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock title %}
    </title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/flatpickr/flatpickr.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'jquery/jquery-ui.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    
    <style>
        #northEpiphyte_1 {
            border: 1;
            border-color: blueviolet;
            margin: 1000px;
        }
    </style>

    {% block styles %}
    {% endblock styles %}

    {% block head_scripts %}
    {% endblock head_scripts %}

</head>
<body>
    {% block initial_js %}
    {% endblock initial_js %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <a class="navbar-brand" href="#">Classifier</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'dashboard' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'specimen:list' %}">Specimens</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'trees:list' %}">Tree Hosts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'locations:list' %}">Locations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'epiphytes:list' %}">Epipyhtes</a>
            </li>
            
            </ul>
            <span class="navbar-text">
            Navbar text with an inline element
            </span>
        </div>
    </nav>
    
    {% block modals %}
    {% endblock modals %}
    
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    
    <script src="{% static 'vendor/flatpickr/flatpickr.min.js' %}"></script>
    <script src="{% static 'vendor/flatpickr/plugins/monthSelect/index.js' %}"></script>

    {% block extra_js %}
    {% endblock extra_js %}
</body>
</html>

templates/default-form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="." method="post">
        {% csrf_token %}
        {% block form %}{% endblock form %}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
{% endblock content %}

templates/preset_form.html
{% load core_extras %}

{% if form.non_field_errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ form.non_field_errors|striptags }}
    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
        <span class="font-weight-light" aria-hidden="true">×</span>
    </button>
    </div>
{% endif %}
{% for field in form %}
    <div class="col-12 mb-3">
    {{ field.label_tag }}
    {% if field.field.required %}
        <em class="text-danger">*</em>
    {% endif %}

    {{ field|addcss:'form-control' }}

    {% for error_message in field.errors %}
        <div class="invalid-feedback">
        <i class="fa fa-exclamation-circle fa-fw"></i> {{ error_message }}
        </div>
    {% endfor %}
    </div>
{% endfor %}
</div>
<hr />