classifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('specimen/', include('specimen.urls')),
    path('trees/', include('trees.urls')),
    path('epiphytes/', include('epiphytes.urls')),
    path('locations/', include('locations.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trees/urls.py
from django.urls import path
from .views import (
    TreeCreateView,
    TreeListView,
    TreeUpdateView,
)


app_name = 'trees'

urlpatterns = [
    path('list/', TreeListView.as_view(),
        name='list'),
    path('create/', TreeCreateView.as_view(),
        name='create'),
    path('<int:pk>/update/', TreeCreateView.as_view(),
        name='update'),
]

trees/models.py
from django.db import models


class Tree(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

trees/forms.py
from django import forms

from .models import Tree


class TreeForm(forms.ModelForm):
    
    class Meta:
        model = Tree
        fields = ['name']

trees/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
)
from .models import Tree
from .forms import (
    TreeForm
)
from django.urls import reverse_lazy


class TreeListView(ListView):
    template_name = 'trees/list-tree.html'
    model = Tree


class TreeCreateView(CreateView):
    '''
    View for adding new trees in the database
    '''

    template_name = 'trees/create-tree.html'
    model = Tree
    form_class = TreeForm
    success_url = reverse_lazy('trees:list')


class TreeUpdateView(UpdateView):
    '''
    View for adding new trees in the database
    '''

    template_name = 'trees/update-tree.html'
    model = Tree
    form_class = TreeForm
    success_url = reverse_lazy('trees:list')

trees/templates/trees/create-tree.html
{% extends 'default-form.html' %}

{% block title %}
    Create Tree
{% endblock title %}

{% block form %}
    {% include 'preset_form.html' %}
{% endblock form %}

trees/templates/trees/list-tree.html
{% extends 'base.html' %}

{% block title %}
    Tree List
{% endblock title %}

{% block content %}
<div class="container">
    <div class="d-flex flex-row-reverse mb-3" id="header-buttons">
        <a href="{% url 'trees:create' %}">
            <button class="btn btn-success">
                Add Tree
            </button>
        </a>
    </div>
    <table class="table table-condensed">
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.name }}</td>
            <td>
                <a class="btn btn-sm btn-icon btn-secondary" href="{% url 'trees:update' object.pk %}">
                    <i class="fa fa-pencil"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
</div>
{% endblock content %}

trees/templates/trees/update-tree.html
{% extends 'default-form.html' %}

{% block title %}
    Update Tree - {{ object.pk }}
{% endblock title %}

{% block form %}
    {% include 'preset_form.html' %}
{% endblock form %}